import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "@/components/ui/accordion";

const faqItems = [
  {
    question: "How to generate a barcode?",
    answer: "Choose a barcode type, enter the data you want to encode, and click the 'Generate Barcode' button. The generated barcode image will be displayed on the page, which you can download or use directly."
  },
  {
    question: "What types of barcodes are supported?",
    answer: "We support a variety of common barcode types, including Code 128, QR Code, EAN-13, and more. You can view all available types in the dropdown menu of the generator."
  },
  {
    question: "What is the quality of the barcode image generated?",
    answer: "The barcode images generated by us are of high quality and can be used for printing and digital display. The image format is PNG, ensuring clarity and compatibility."
  },
  {
    question: "Do I need to pay to use this tool?",
    answer: "The basic barcode generation function is free. For advanced features or bulk generation, we offer paid plans. Please check our pricing page for details."
  },
];

const FAQ = () => {
  return (
    <section id="faq" className="py-12">
      <div className="container mx-auto px-4">
        <h2 className="text-3xl font-bold mb-6 text-center">Frequently asked questions</h2>
        <Accordion type="single" collapsible>
          {faqItems.map((item, index) => (
            <AccordionItem key={index} value={`item-${index}`}>
              <AccordionTrigger>{item.question}</AccordionTrigger>
              <AccordionContent>{item.answer}</AccordionContent>
            </AccordionItem>
          ))}
        </Accordion>
      </div>
    </section>
  );
};

export default FAQ;